POSTTEST 4
Nama : Millania Zahroh
NIM : 2009106140

In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

# untuk Data Split
from sklearn.model_selection import train_test_split #testing dan training data
# untuk Data Transforming
from sklearn.preprocessing import StandardScaler #standarisasi
from sklearn.preprocessing import MinMaxScaler #normalisasi
# untuk Data Cleaning
from sklearn.impute import SimpleImputer #subtitusi nilai
# untuk Data Encoding
from sklearn.preprocessing import OrdinalEncoder #encoder
from sklearn.preprocessing import OneHotEncoder #onehot

In [3]:
df = pd.read_csv('Social_Network_Ads.csv')
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [5]:
df.isna().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [6]:
print(f'panjang dataset {len(df)} baris')

panjang dataset 400 baris


In [8]:
data = df[['User ID']]
label = df['Age']

data_train, data_test, label_train, label_test = train_test_split(data, label, test_size=.3)

In [9]:
print(f'panjang data training {len(data_train)}',
     f'panjang label training {len(label_train)}',
     f'panjang data testing {len(data_test)}',
     f'panjang label testing {len(label_test)}',
     sep='\n')

panjang data training 280
panjang label training 280
panjang data testing 120
panjang label testing 120


In [10]:
dataset_normalisasi = df.copy()
dataset_standarirasi = df.copy()

NORMALISASI

In [12]:
scaler = MinMaxScaler()

normalize_dataset = scaler.fit_transform(dataset_normalisasi[['User ID', 'Age']])

normalize_dataset = pd.DataFrame(normalize_dataset)
normalize_dataset.rename(columns={ 0 :'User ID', 1 : 'Age'}, inplace=True)

normalize_dataset.head(5)

User ID       Age
0  0.232636  0.023810
1  0.982732  0.404762
2  0.409926  0.190476
3  0.147083  0.214286
4  0.954801  0.023810

STANDARISASI

In [13]:
dataset_standarirasi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [14]:
dataset_standarirasi.drop('Gender', axis = 1, inplace= True)

In [15]:
dataset_standarirasi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User ID          400 non-null    int64
 1   Age              400 non-null    int64
 2   EstimatedSalary  400 non-null    int64
 3   Purchased        400 non-null    int64
dtypes: int64(4)
memory usage: 12.6 KB


In [16]:
standart_std = StandardScaler()

scaled_data = standart_std.fit_transform(dataset_standarirasi)

print('Dataset sebelum scalling:',  # SEBELUM
      f'Nilai standar deviasi:\n{np.std(dataset_standarirasi)}',
      sep='\n', end='\n\n')

print('Dataset setelah scalling:',  # SESUDAH
      scaled_data[:6],
      f'Nilai standar deviasi: {np.std(scaled_data)}',
      sep='\n')

Dataset sebelum scalling:
Nilai standar deviasi:
User ID            71568.692626
Age                   10.469765
EstimatedSalary    34054.312410
Purchased              0.479264
dtype: float64

Dataset setelah scalling:
[[-0.93657932 -1.78179743 -1.49004624 -0.74593581]
 [ 1.66838653 -0.25358736 -1.46068138 -0.74593581]
 [-0.32087714 -1.11320552 -0.78528968 -0.74593581]
 [-1.23369247 -1.01769239 -0.37418169 -0.74593581]
 [ 1.57138881 -1.78179743  0.18375059 -0.74593581]
 [ 0.52024483 -1.01769239 -0.34481683 -0.74593581]]
Nilai standar deviasi: 1.0


DATA CLEANING

In [17]:
dataset_ns = df.copy()

In [18]:
imputer_mean = SimpleImputer(strategy='mean')
imputer_median = SimpleImputer(strategy='median')
imputer_modus = SimpleImputer(strategy='most_frequent')

MODUS

In [19]:
df.isna().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [20]:
dfmodus = df.copy()

In [22]:
dfmodus['Gender'] = imputer_modus.fit_transform(dfmodus[['Gender']])
dfmodus.isna().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

MEAN

In [24]:
dfmodus['Gender'] = imputer_modus.fit_transform(dfmodus[['Gender']])
dfmodus.isna().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [31]:
df2 = pd.read_csv('Social_Network_Ads.csv')
df2.head()
dataset_duplicate = df2.age()

dataset_duplicate.duplicated().sum()

AttributeError: 'DataFrame' object has no attribute 'age'

In [32]:
dataset_duplicate.drop_duplicates(inplace=True)

dataset_duplicate.duplicated().sum()

NameError: name 'dataset_duplicate' is not defined

In [33]:
dataset_ordinal = df.copy()
dataset_one_hot = df.copy()

In [34]:
df['Age'].unique()

array([19, 35, 26, 27, 32, 25, 20, 18, 29, 47, 45, 46, 48, 49, 31, 21, 28,
       33, 30, 23, 24, 22, 59, 34, 39, 38, 37, 42, 40, 36, 41, 58, 55, 52,
       60, 56, 53, 50, 51, 57, 44, 43, 54], dtype=int64)

In [35]:
encoder_ordinal =OrdinalEncoder()

# di encoding
dataset_ordinal['Age'] = encoder_ordinal.fit_transform(dataset_ordinal[['Age']]).astype('int64')

dataset_ordinal.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male    1            19000          0
1  15810944    Male   17            20000          0
2  15668575  Female    8            43000          0
3  15603246  Female    9            57000          0
4  15804002    Male    1            76000          0

In [37]:
dataset_ordinal['User ID'].unique()

array([15624510, 15810944, 15668575, 15603246, 15804002, 15728773,
       15598044, 15694829, 15600575, 15727311, 15570769, 15606274,
       15746139, 15704987, 15628972, 15697686, 15733883, 15617482,
       15704583, 15621083, 15649487, 15736760, 15714658, 15599081,
       15705113, 15631159, 15792818, 15633531, 15744529, 15669656,
       15581198, 15729054, 15573452, 15776733, 15724858, 15713144,
       15690188, 15689425, 15671766, 15782806, 15764419, 15591915,
       15772798, 15792008, 15715541, 15639277, 15798850, 15776348,
       15727696, 15793813, 15694395, 15764195, 15744919, 15671655,
       15654901, 15649136, 15775562, 15807481, 15642885, 15789109,
       15814004, 15673619, 15595135, 15583681, 15605000, 15718071,
       15679760, 15654574, 15577178, 15595324, 15756932, 15726358,
       15595228, 15782530, 15592877, 15651983, 15746737, 15774179,
       15667265, 15655123, 15595917, 15668385, 15709476, 15711218,
       15798659, 15663939, 15694946, 15631912, 15768816, 15682

In [38]:
temp_dataset = pd.get_dummies(dataset_one_hot[['User ID']])

temp_dataset = pd.DataFrame(temp_dataset)

dataset_one_hot.drop('User ID', axis=1, inplace=True)

dataset_one_hot = dataset_one_hot.join(temp_dataset)
dataset_one_hot.head(5)

Gender  Age  EstimatedSalary  Purchased   User ID
0    Male   19            19000          0  15624510
1    Male   35            20000          0  15810944
2  Female   26            43000          0  15668575
3  Female   27            57000          0  15603246
4    Male   19            76000          0  15804002