POSTTEST 7 

Nama : Millania Zahroh

NIM  : 2009106140

In [112]:
import tensorflow as tf
import numpy as np

Membuat sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan di variable random_tensor

In [113]:
random_tensor = tf.random.normal([5,5], mean=2., stddev=5., seed=1)
random_tensor.numpy()

array([[ 2.02671  , -3.230219 , -6.2138243,  0.2523315,  6.757255 ],
       [ 6.0529137, -1.8087049,  7.068322 , -7.2351074,  3.0085888],
       [ 8.086762 , -6.7871304, 10.82916  ,  7.7002   ,  6.158907 ],
       [-7.987301 ,  3.258838 ,  7.344916 ,  3.5079923,  3.3209865],
       [ 2.1158302,  5.6114187,  3.8723116,  1.5220953,  9.092854 ]],
      dtype=float32)

In [114]:
list_utt = [[1,3,5,7,9],[11,13,15,17,19],[21,23,25,27,29],[31,33,35,37,39],[41,43,45,47,49]]

utt = tf.convert_to_tensor(list_utt)
utt.numpy()

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

Slicing

In [115]:
slicing = tf.random.normal([5,5,5])
slicing.numpy()

array([[[ 0.78638065, -0.75815547,  0.27119565,  0.9974266 ,
         -0.54590315],
        [-2.0451512 ,  0.12828982,  1.4906409 ,  0.7682289 ,
          0.65665567],
        [ 0.25843298,  1.0701345 ,  0.93951565, -1.5787479 ,
         -1.6174239 ],
        [-0.07817815,  1.396611  ,  1.0033491 ,  0.8887313 ,
          0.04807568],
        [-0.6992763 , -0.9467381 ,  1.7748348 ,  0.01255743,
          0.41172665]],

       [[-0.74413687,  2.2621307 ,  2.0271912 , -0.51846683,
         -0.37950215],
        [-0.48303893, -0.63177794, -0.7434608 ,  0.5148944 ,
         -2.007295  ],
        [-1.4039257 ,  0.3674582 ,  0.9869303 , -1.8080088 ,
          0.37657553],
        [-1.2953317 ,  0.20160617, -0.3056423 ,  0.39536244,
          0.6627734 ],
        [ 0.4568802 ,  1.481022  , -1.6529326 ,  1.0591874 ,
          2.0128982 ]],

       [[ 0.33970442, -0.830786  ,  0.6860306 , -0.07446154,
          0.65991443],
        [ 1.4982294 ,  1.6307356 , -0.9330077 ,  1.0110312 ,
         -0

In [116]:
slicing[3,3,3]

<tf.Tensor: shape=(), dtype=float32, numpy=0.36443833>

In [117]:

slicing[3]


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-1.1620096 ,  1.5678296 , -0.67065084,  0.5027863 ,  0.12024327],
       [-0.3673789 , -1.6304309 , -1.158086  , -0.650678  ,  3.3539336 ],
       [ 0.831597  ,  1.8496542 ,  0.02412421,  0.60372764,  1.0267569 ],
       [ 1.1595788 , -1.473556  , -0.16598581,  0.36443833,  1.2822449 ],
       [-1.3360822 ,  0.80111855, -0.9304521 , -1.5713643 ,  1.1792579 ]],
      dtype=float32)>

In [118]:
tf.gather(slicing, indices=[3,3,3]).numpy()

array([[[-1.1620096 ,  1.5678296 , -0.67065084,  0.5027863 ,
          0.12024327],
        [-0.3673789 , -1.6304309 , -1.158086  , -0.650678  ,
          3.3539336 ],
        [ 0.831597  ,  1.8496542 ,  0.02412421,  0.60372764,
          1.0267569 ],
        [ 1.1595788 , -1.473556  , -0.16598581,  0.36443833,
          1.2822449 ],
        [-1.3360822 ,  0.80111855, -0.9304521 , -1.5713643 ,
          1.1792579 ]],

       [[-1.1620096 ,  1.5678296 , -0.67065084,  0.5027863 ,
          0.12024327],
        [-0.3673789 , -1.6304309 , -1.158086  , -0.650678  ,
          3.3539336 ],
        [ 0.831597  ,  1.8496542 ,  0.02412421,  0.60372764,
          1.0267569 ],
        [ 1.1595788 , -1.473556  , -0.16598581,  0.36443833,
          1.2822449 ],
        [-1.3360822 ,  0.80111855, -0.9304521 , -1.5713643 ,
          1.1792579 ]],

       [[-1.1620096 ,  1.5678296 , -0.67065084,  0.5027863 ,
          0.12024327],
        [-0.3673789 , -1.6304309 , -1.158086  , -0.650678  ,
          3

In [119]:
tf.gather_nd(slicing, indices=[[0,2,2],[1,2,2],[2,2,2],[3,2,2],[4,2,2]]).numpy()

array([ 0.93951565,  0.9869303 , -0.29158542,  0.02412421, -0.24458683],
      dtype=float32)

Membuat sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima di variable prime_tensor

In [120]:
list_prime = [[2, 3, 5, 7, 11],[13, 17, 19, 23, 29],[31, 37, 41, 43, 47],[53, 59, 61, 71, 73],[79, 83, 89, 97, 1]]

prime_tensor = tf.constant(list_prime, dtype=tf.float32)
prime_tensor.numpy()

array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 71., 73.],
       [79., 83., 89., 97.,  1.]], dtype=float32)

Tampilkan dimensi dari kedua variable tersebut

In [121]:
random_tensor.shape

TensorShape([5, 5])

In [122]:
prime_tensor.shape

TensorShape([5, 5])

Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)

In [123]:
print("1. Penjumlahan :",tf.add(prime_tensor,random_tensor))
print("\n2. Pengurangan :",tf.subtract(prime_tensor,random_tensor))
print("\n3. Perkalian :",tf.multiply(prime_tensor,random_tensor))
print("\n4. Pembagian :",tf.divide(prime_tensor,random_tensor))
print("\n5. Pangkat :",tf.pow(prime_tensor,random_tensor))


1. Penjumlahan : tf.Tensor(
[[ 4.02671    -0.23021889 -1.2138243   7.2523317  17.757256  ]
 [19.052914   15.191296   26.068321   15.764893   32.00859   ]
 [39.08676    30.21287    51.82916    50.7002     53.158905  ]
 [45.0127     62.25884    68.34492    74.507996   76.320984  ]
 [81.11583    88.61142    92.872314   98.522095   10.092854  ]], shape=(5, 5), dtype=float32)

2. Pengurangan : tf.Tensor(
[[-2.6710033e-02  6.2302189e+00  1.1213824e+01  6.7476683e+00
   4.2427449e+00]
 [ 6.9470863e+00  1.8808704e+01  1.1931678e+01  3.0235107e+01
   2.5991411e+01]
 [ 2.2913239e+01  4.3787132e+01  3.0170841e+01  3.5299801e+01
   4.0841095e+01]
 [ 6.0987301e+01  5.5741161e+01  5.3655083e+01  6.7492004e+01
   6.9679016e+01]
 [ 7.6884171e+01  7.7388580e+01  8.5127686e+01  9.5477905e+01
  -8.0928535e+00]], shape=(5, 5), dtype=float32)

3. Perkalian : tf.Tensor(
[[   4.05342     -9.690657   -31.069122     1.7663205   74.3298   ]
 [  78.68788    -30.747982   134.29813   -166.40747     87.24908  ]
 [ 

Tampilkan nilai maksimal dan minimal dari variable random_tensor

In [124]:
tf.argmax(random_tensor, axis=0).numpy() # max baris random_tensor

array([2, 4, 2, 2, 4], dtype=int64)

In [125]:
tf.argmax(random_tensor, axis=1).numpy() # max kolom 

array([4, 2, 2, 2, 4], dtype=int64)

In [126]:
tf.argmin(random_tensor, axis=0).numpy() # min baris random_tensor

array([3, 2, 0, 1, 1], dtype=int64)

In [127]:
tf.argmin(random_tensor, axis=1).numpy()  # min kolom 

array([2, 3, 1, 0, 3], dtype=int64)

Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [128]:
tf.concat([random_tensor,prime_tensor], axis=0).numpy() # penggabungan baris

array([[ 2.02671  , -3.230219 , -6.2138243,  0.2523315,  6.757255 ],
       [ 6.0529137, -1.8087049,  7.068322 , -7.2351074,  3.0085888],
       [ 8.086762 , -6.7871304, 10.82916  ,  7.7002   ,  6.158907 ],
       [-7.987301 ,  3.258838 ,  7.344916 ,  3.5079923,  3.3209865],
       [ 2.1158302,  5.6114187,  3.8723116,  1.5220953,  9.092854 ],
       [ 2.       ,  3.       ,  5.       ,  7.       , 11.       ],
       [13.       , 17.       , 19.       , 23.       , 29.       ],
       [31.       , 37.       , 41.       , 43.       , 47.       ],
       [53.       , 59.       , 61.       , 71.       , 73.       ],
       [79.       , 83.       , 89.       , 97.       ,  1.       ]],
      dtype=float32)

In [129]:
tf.concat([random_tensor,prime_tensor], axis=1).numpy() # penggabungan kolom

array([[ 2.02671  , -3.230219 , -6.2138243,  0.2523315,  6.757255 ,
         2.       ,  3.       ,  5.       ,  7.       , 11.       ],
       [ 6.0529137, -1.8087049,  7.068322 , -7.2351074,  3.0085888,
        13.       , 17.       , 19.       , 23.       , 29.       ],
       [ 8.086762 , -6.7871304, 10.82916  ,  7.7002   ,  6.158907 ,
        31.       , 37.       , 41.       , 43.       , 47.       ],
       [-7.987301 ,  3.258838 ,  7.344916 ,  3.5079923,  3.3209865,
        53.       , 59.       , 61.       , 71.       , 73.       ],
       [ 2.1158302,  5.6114187,  3.8723116,  1.5220953,  9.092854 ,
        79.       , 83.       , 89.       , 97.       ,  1.       ]],
      dtype=float32)

Tampilkan hasil sorting dari kedua variable di atas. (descending)

In [130]:
sort_random_tensor1 = tf.sort(random_tensor, direction="DESCENDING")
sort_random_tensor1.numpy()

array([[ 6.757255 ,  2.02671  ,  0.2523315, -3.230219 , -6.2138243],
       [ 7.068322 ,  6.0529137,  3.0085888, -1.8087049, -7.2351074],
       [10.82916  ,  8.086762 ,  7.7002   ,  6.158907 , -6.7871304],
       [ 7.344916 ,  3.5079923,  3.3209865,  3.258838 , -7.987301 ],
       [ 9.092854 ,  5.6114187,  3.8723116,  2.1158302,  1.5220953]],
      dtype=float32)

In [131]:
sort_random_tensor2 = tf.argsort(random_tensor, direction="DESCENDING")
sort_random_tensor2.numpy()

array([[4, 0, 3, 1, 2],
       [2, 0, 4, 1, 3],
       [2, 0, 3, 4, 1],
       [2, 3, 4, 1, 0],
       [4, 1, 2, 0, 3]])

In [132]:
sort_prime_tensor1 = tf.sort(prime_tensor, direction="DESCENDING")
sort_prime_tensor1.numpy()

array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [73., 71., 61., 59., 53.],
       [97., 89., 83., 79.,  1.]], dtype=float32)

In [133]:
sort_prime_tensor2 = tf.argsort(prime_tensor, direction="DESCENDING")
sort_prime_tensor2.numpy()

array([[4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [3, 2, 1, 0, 4]])